<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>custom-select_team-leader-search</name>
   <tag></tag>
   <elementGuidId>db91a63a-fd75-41ca-8c4d-51c43fcb81d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//custom-select[@items=&quot;team.search&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>custom-select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//custom-select[@items=&quot;team.search&quot;]</value>
   </webElementProperties>
</WebElementEntity>
