<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>custom-select_new-competition-importance</name>
   <tag></tag>
   <elementGuidId>94ff109b-23f3-4698-84e1-52a975a975ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//custom-select[@model = 'addingAthlete.importance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>custom-select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>items</name>
      <type>Main</type>
      <value>importances</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>model</name>
      <type>Main</type>
      <value>addingAthlete.importance</value>
   </webElementProperties>
</WebElementEntity>
