<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Squat</name>
   <tag></tag>
   <elementGuidId>a560689c-060b-4988-90d1-e9d739d8f84c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@ng-repeat=&quot;item in sortedItems&quot;]//span[text()=&quot;Squat&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>item[nameField]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Squat</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;team-test-overview&quot;)/div[@class=&quot;team-test-header-bar&quot;]/custom-select[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;btn-group open&quot;]/ul[@class=&quot;dropdown-menu single-button ng-scope opened&quot;]/li[@class=&quot;ng-scope&quot;]/a[1]/span[@class=&quot;ng-binding&quot;]</value>
   </webElementProperties>
</WebElementEntity>
