<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_md-thumb</name>
   <tag></tag>
   <elementGuidId>9cd9b3bc-6e97-4eba-bebb-86750b0f48b9</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;single-set&quot;]/div[@class=&quot;rest&quot;]/div[@class=&quot;toggle-btn&quot;]/md-switch[not(contains(@class,&quot;md-checked&quot;))]/div[@class=&quot;md-container&quot;]/div[@class=&quot;md-thumb-container&quot;]/div[@class=&quot;md-thumb&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-thumb</value>
   </webElementProperties>
</WebElementEntity>
