<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Insert</name>
   <tag></tag>
   <elementGuidId>76a039e9-3860-4c89-a28e-ae5766841ed3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;body-grid-view ng-scope selected&quot;]//button[@ng-click=&quot;save()&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>selectedItem.phaseId == item.phaseId &amp;&amp; currentMenu.name == 'Phases'</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>save()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-default-theme md-button primary-btn print-btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Insert</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-scope&quot;]/div[@class=&quot;md-dialog-container ng-scope&quot;]/md-dialog[@class=&quot;add-existing-phase-popup md-default-theme transition-in&quot;]/div[@class=&quot;content-move-block&quot;]/section[@id=&quot;content-manager-new&quot;]/div[@class=&quot;library-content-manager&quot;]/div[@class=&quot;library-menu&quot;]/div[@class=&quot;library-content&quot;]/div[@class=&quot;right-menu&quot;]/div[@class=&quot;gird-view-all&quot;]/div[@class=&quot;scrollable&quot;]/div[@class=&quot;body-grid-view ng-scope selected&quot;]/div[@class=&quot;items view&quot;]/button[@class=&quot;md-default-theme md-button primary-btn print-btn&quot;]</value>
   </webElementProperties>
</WebElementEntity>
