<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Today</name>
   <tag></tag>
   <elementGuidId>23c1253f-5d4c-4396-b377-7973cb5ec365</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Today' or . = 'Today')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc-day-number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendarPopup&quot;)/div[@class=&quot;fc-content&quot;]/div[@class=&quot;fc-view fc-view-month fc-grid&quot;]/table[@class=&quot;fc-border-separate&quot;]/tbody[1]/tr[@class=&quot;fc-week&quot;]/td[@class=&quot;fc-day fc-wed fc-widget-content fc-today fc-state-highlight&quot;]/div[1]/div[@class=&quot;fc-day-number&quot;]</value>
   </webElementProperties>
</WebElementEntity>
