<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Walkme_Close</name>
   <tag></tag>
   <elementGuidId>ea4b5530-7a44-4d90-a82e-2e63f2453885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,&quot;wm-shoutout&quot;)]//span[contains(@class,&quot;wm-close-link&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>walkme-action-destroy-1 wm-close-link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wm-shoutout-61186&quot;)/div[@class=&quot;wm-content&quot;]/div[@class=&quot;buttons-wrapper&quot;]/span[@class=&quot;walkme-action-destroy-1 wm-close-link&quot;]</value>
   </webElementProperties>
</WebElementEntity>
