<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_unselector new-positive-Distance_2</name>
   <tag></tag>
   <elementGuidId>e91e69bc-228f-46c8-b936-704645a3c5dc</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>checkNumber(blockSet, name)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>50000</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>variables.isDisabled || data.isCompleted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>(blockSet['has'+variables.params[name].name]!='Rmax' &amp;&amp; blockSet['has'+variables.params[name].name]!='Rmin' &amp;&amp; name!='time') &amp;&amp; ((name =='reps' &amp;&amp; variables.params['weight'].unit == 'curves' &amp;&amp; blockSet['has'+variables.params[name].name]!='Rmax' &amp;&amp; blockSet['has'+variables.params[name].name]!='Rmin')|| (name !='reps' &amp;&amp; variables.params['weight'].unit == 'curves' &amp;&amp; blockSet.type!='Required'  &amp;&amp; blockSet['has'+variables.params[name].name]!='Rmax' &amp;&amp; blockSet['has'+variables.params[name].name]!='Rmin') || (name !='reps' &amp;&amp; variables.params['weight'].unit == 'curves' &amp;&amp; blockSet.type=='Required'  &amp;&amp; blockSet['has'+variables.params[name].name]!='Rmax' &amp;&amp; blockSet['has'+variables.params[name].name]!='Rmin') || (name =='reps' &amp;&amp; variables.params['weight'].unit != 'curves' &amp;&amp; blockSet['has'+variables.params[name].name]!='Rmax' &amp;&amp; blockSet['has'+variables.params[name].name]!='Rmin') || (name !='reps' &amp;&amp; variables.params['weight'].unit != 'curves' &amp;&amp; blockSet['has'+variables.params[name].name]!='Rmax' &amp;&amp; blockSet['has'+variables.params[name].name]!='Rmin') || (name !='reps' &amp;&amp; variables.params['weight'].unit != 'curves' &amp;&amp; blockSet['has'+variables.params[name].name]!='Rmax' &amp;&amp; blockSet['has'+variables.params[name].name]!='Rmin'))</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exercise-content&quot;)/exercise-editor-blocksets[@class=&quot;scrollable unselector ng-isolate-scope&quot;]/div[@class=&quot;exercise-editor-blocksets unselector&quot;]/div[@class=&quot;unselector ng-pristine ng-untouched ng-valid ng-isolate-scope ui-sortable sortable&quot;]/div[@class=&quot;single-row ng-scope&quot;]/div[@class=&quot;single-set&quot;]/div[@class=&quot;values&quot;]/div[1]/div[@class=&quot;single-value distance-2&quot;]/input[@class=&quot;unselector new-positive-number distance-2 number-only&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>blockSet[name+'Display']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>updateBlockSetParam(blockSet, name)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'number-only': name!='reps'}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is-integer</name>
      <type>Main</type>
      <value>name=='reps'</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unselector new-positive-number distance-2 number-only</value>
   </webElementProperties>
</WebElementEntity>
