<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Absolute</name>
   <tag></tag>
   <elementGuidId>70929d22-d624-4501-8f67-2123610c253d</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exercise-content&quot;)/exercise-editor-param-selector[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;exercise-editor-param-selector&quot;]/div[@class=&quot;params-results&quot;]/div[1]/div[2]/div[1]/div[@class=&quot;text-center single-param ng-scope&quot;]/span[@class=&quot;unit&quot;]/custom-select[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;btn-group open&quot;]/ul[@class=&quot;dropdown-menu single-button ng-scope opened&quot;]/li[@class=&quot;ng-scope&quot;]/a[1]/span[@class=&quot;ng-binding&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>item[nameField]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Absolute</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
   </webElementProperties>
</WebElementEntity>
