<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Templates</name>
   <tag></tag>
   <elementGuidId>9b3d6755-9707-4407-9188-5fc3ffc8d9d7</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/nav[@class=&quot;multilevelpushmenu_wrapper ltr&quot;]/div[@class=&quot;levelHolderClass ng-isolate-scope visible multilevelpushmenu_inactive level-0&quot;]/div[@class=&quot;item-container&quot;]/ul[@class=&quot;ng-scope invisible&quot;]/li[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/recursive[1]/div[@class=&quot;levelHolderClass ng-scope ng-isolate-scope visible&quot;]/div[1]/div[@id=&quot;element-template&quot;]/div[@class=&quot;filter-options&quot;]/button[@class=&quot;md-button md-default-theme active&quot;]/span[@class=&quot;ng-scope&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Templates</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
   </webElementProperties>
</WebElementEntity>
