<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_add-block-btns</name>
   <tag></tag>
   <elementGuidId>6b82475b-c8d8-42e1-8f16-47a8c71751a0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>layout</name>
      <type>Main</type>
      <value>layout</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>layout-align</name>
      <type>Main</type>
      <value>start center</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'show-personalize-box': (global.isAddingPersonalizedBlock || global.isAddingTemplateBlockNew) &amp;&amp; global.workoutToAddBlock == workoutId &amp;&amp; global.weekToAddBlock == weekNumber, disable: data.isCompleted}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-block-btns</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;week-149002-1&quot;)/div[@class=&quot;days clearfix unselector ng-pristine ng-untouched ng-valid ng-isolate-scope ui-sortable day-sortable&quot;]/div[@class=&quot;day ng-scope&quot;]/div[@class=&quot;day-contain&quot;]/div[@class=&quot;add-block-btns&quot;]</value>
   </webElementProperties>
</WebElementEntity>
