<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Template</name>
   <tag></tag>
   <elementGuidId>c9ba9ed0-ab72-476e-9b3a-855749c23eb4</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!organizationSettings.settings.enableBlockProgressions &amp;&amp; currentPhase.phases.isBlockProgression == 'N'</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>openTemplateBlock($event, workoutId, weekNumber);closeAllEditField()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-button md-default-theme ng-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+Template</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;week-149002-1&quot;)/div[@class=&quot;days clearfix unselector ng-pristine ng-untouched ng-valid ng-isolate-scope ui-sortable day-sortable&quot;]/div[@class=&quot;day ng-scope&quot;]/div[@class=&quot;day-contain&quot;]/div[@class=&quot;add-block-btns&quot;]/div[@class=&quot;btns&quot;]/div[@class=&quot;md-button md-default-theme ng-scope&quot;]</value>
   </webElementProperties>
</WebElementEntity>
