<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_template-1</name>
   <tag></tag>
   <elementGuidId>e43c9847-6b0c-4260-b666-4019f2be9436</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/nav[@class=&quot;multilevelpushmenu_wrapper ltr&quot;]/div[@class=&quot;levelHolderClass ng-isolate-scope visible multilevelpushmenu_inactive level-0&quot;]/div[@class=&quot;item-container&quot;]/ul[@class=&quot;ng-scope invisible&quot;]/li[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/recursive[1]/div[@class=&quot;levelHolderClass ng-scope ng-isolate-scope visible&quot;]/div[@class=&quot;item-container&quot;]/ul[@class=&quot;ng-scope&quot;]/li[@class=&quot;ng-scope is-single&quot;]/a[@class=&quot;ng-scope&quot;]/strong[@class=&quot;ng-binding&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
   </webElementProperties>
</WebElementEntity>
